image: alpine:latest

before_script: |
  apk update
  apk add git nodejs npm

pages:
  stage: deploy
  script: |
    for App in WuppiMini
    do
      mkdir ./public/${App}
      cd ./src/${App}
      npm update
      npm install
      node ./index.js html
      cp ./index.js ./index.html ./node_modules/SpaccDotWeb/SpaccDotWeb.Server.js ../../public/${App}/
      cd ../..
    done
    cd ./public
    node ../WriteRedirectPages.js
  artifacts:
    paths:
    - public
  only:
  - master
