image: alpine:latest

before_script: |
  apk update
  apk add git nodejs npm

pages:
  stage: deploy
  script: |
    mkdir ./public/WuppiMini
    cd ./src/WuppiMini
    npm update
    npm install
    node ./index.js html
    cp ./index.js ./index.html ./node_modules/SpaccDotWeb/SpaccDotWeb.Server.js ../../public/WuppiMini/
  artifacts:
    paths:
    - public
  only:
  - master
